[workspace]
name = "ca_web"
version = "0.1.1"
description = "Testing a2svior's lightbug_http web server package"
authors = ["Carl Caulkett <carl.caulkett@gmail.com>"]
platforms = ["osx-arm64"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community"
]
preview = ["pixi-build"]

[tasks]
default = "pixi run mojo -I /Volumes/PRO-G40/Code/Mojo/lightbug_http client.mojo"

[dependencies]
mojo = "==0.25.6"
